# Generated by Django 3.2.9 on 2023-01-14 17:20

from django.db import migrations
from Clear.models import Inhalers


def InsertInhalers(apps, schema_editor):
    Inhalers.objects.create(name="Beclametasone Dipropionate")
    Inhalers.objects.create(name="Ciclesonide")
    Inhalers.objects.create(name="Fluticasone Poprionate")
    Inhalers.objects.create(name="Beclometasone")
    Inhalers.objects.create(name="Budesonide")
    Inhalers.objects.create(name="Fluticasone Poprionate")
    Inhalers.objects.create(name="Mometasone")
    Inhalers.objects.create(name="Beclometasone Dipropionate with Ormoterol")
    Inhalers.objects.create(name="Budesonid with Formoterol")
    Inhalers.objects.create(name="Fluticasone Poprionate with Formoterol")
    Inhalers.objects.create(name="Fluticasone Poprionate with Salmeterol")
    Inhalers.objects.create(name="Fluticasone Furoate with Vilanterol")


class Migration(migrations.Migration):

    dependencies = [
        ('Clear', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(InsertInhalers),
    ]
